name: Release with changelog and version bump
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to set (if empty, action increases previous release minnor version)'
        required: false
        default: ''
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: lavr/action-release@master
      id: runactionrelease
      name: Run action-release
      with:
        version: ${{ github.event.inputs.version }}
    - run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add release
        git commit -m "release"
        git push
    - name: Echo result
      run: |
        echo "${{ steps.runactionrelease.outputs.version }}"

